### ISSUE TITLE
ประชุมกลุ่มเพื่อเลือกหัวข้อโครงาาน

### ISSUE THREAD

**Issue by SCKagura** [SCKagura/cpe103-test-group-20#1]

**Comment by kaewtar** [comment]
เกมวิ่งขึ้นดอยมั้ย

**Comment by weerr12** [comment]
ลองพวกเกมทำลายมิตรภาพดูมั้ยเพื่อนๆ

**Comment by SCKagura** [comment]
มีเสนอแนวคล้ายๆ 3 เกม 
1.หมากล้อมจีน
2.แนวต่อสู้ 2 คนแบบ shadow fight 
3.แนวยิงกัน2 คนแบบ gun mayhem
ลงอหาดูในเน็ตดูได้ สิ่งที่เราต้องออกแบบตัวแผนที่กับตัวละครน่าสนใจ เดี๋ยวเรื่องโค้ด จะนั่งจัดการให้ 
มีอะไรเสนอเพิ่มอีกไหม

**Comment by SCKagura** [comment]
หรืออยากทำเกมง่ายๆกว่านี้ก็ได้ เพราะรู้สึกมันเข้าขั้นยากเลย

**Comment by kaewtar** [comment]
แนวยิงกัน 2 คนก็น่าสนใจดีนะ

**Comment by weerr12** [comment]
เห็นด้วยๆ เกมยิงกันสองคน ดูแข่งขันกันดีนะ

**Comment by SCKagura** [comment]
เสนอมาได้เลย หลายๆแนวละมาโหวต

**Comment by kaewtar** [comment]
ถ้ายิงกันเพื่อหาคนที่ขึ้นไปได้สูงที่สุดบนยอดดอยล่ะ

**Comment by Phurinon** [comment]
เกมยิงกันก็น่าสนนะ แต่เราก็ต้องทำให้มันน่าสนใจกว่าที่มีในออนไลน์ทั่วไปแบบที่อาจารย์บอกปะ

**Comment by Phurinon** [comment]
https://scratch.mit.edu/projects/546815153/

**Comment by Phurinon** [comment]
เราทำเกมประมาณนี่มั้ย แล้วเปลี่ยน theme เช่น ให้วิ่งกลับหอ

**Comment by kaewtar** [comment]
น่าสนใจเลยนะ 
ถ้าเป็น theme ไปเรียนคาบต่อไป หาตึกเรียนในวันเปิดเรียนวันแรกล่ะ

**Comment by Phurinon** [comment]
![E2DB39AC-85DC-41B6-A429-AC7DC3884FC9](https://user-images.githubusercontent.com/110959150/188325492-3db092cc-4ea3-40d0-850f-c253a7d658e4.jpeg)

**Comment by Phurinon** [comment]
รายละเอียดเกมที่คุยกันมีประมาณนี้

**Comment by Phurinon** [comment]
![16D9BFC2-3634-4DC6-B10C-D5D744EB78B0](https://user-images.githubusercontent.com/110959150/188325694-c138c77b-b366-42bd-8212-3ef733905c7d.jpeg)
หน้าที่ของแต่ละคน
