### ISSUE TITLE
UI (sprite)

### ISSUE THREAD

**Issue by Phurinon** [SCKagura/cpe103-test-group-20#10]

**Comment by kaewtar** [comment]
https://www.canva.com/design/DAFMGgVKV5U/YWEXikamDquasy4HWXP06w/edit

**Comment by kaewtar** [comment]
https://www.canva.com/design/DAFMLbI-EFg/rHDni9IRBkGaXn-WK5BsZg/edit

**Comment by kaewtar** [comment]
ปุ่มอันดับ
