### ISSUE TITLE
ปัญหาที่ต้องแก้ระหว่างการสร้างเกม 

### ISSUE THREAD

**Issue by weerr12** [SCKagura/cpe103-test-group-20#21]

**Comment by weerr12** [comment]
การสร้างสิ่งกีดขวางออกมาพร้อมๆกันสองเลน ยังติดปัญหาอยู่

**Comment by weerr12** [comment]
เวลาเข้าเส้นชัยแล้ว สิ่งกีดขวางยังไม่ยอมหยุดเลย ยังติดบัคตรงนี้

**Comment by weerr12** [comment]
นาฬิกาที่ใช้เพิ่มเวลา ยังติดบัค ตรงเวลาเข้าเส้นชัยแล้วยังไม่ยอมหยุด

**Comment by weerr12** [comment]
บัคด่าน 3 หนักเลยสิ่งกีดขวางไม่โผล่

**Comment by SCKagura** [comment]
แก้หมดแล้วนะ
