### ISSUE TITLE
ออกแบบฉากและตัวละคร

### ISSUE THREAD

**Issue by Phurinon** [SCKagura/cpe103-test-group-20#5]

**Comment by kaewtar** [comment]
![S__3039283](https://user-images.githubusercontent.com/110950048/189473430-2772e2b9-c9b0-4c2e-a2cd-0c540ab97c93.png)
![S__3039284](https://user-images.githubusercontent.com/110950048/189473433-f941d8ec-9b2e-4ddb-9ef9-8eb08190abe8.png)
![S__3039285](https://user-images.githubusercontent.com/110950048/189473434-5fc40046-a469-48aa-b162-519956a2194d.png)

**Comment by kaewtar** [comment]
ตัวละครวาดยากมาก จนตอนนี้ก็ยังวาดไม่ได้เลยอ่ะ ตัวจริงเราขอเวลาวาดนานหน่อยนะ

**Comment by kaewtar** [comment]
เลยวาดอันนี้มาให้ใช้แทนก่อนนะ

**Comment by kaewtar** [comment]
@SCKagura

**Comment by SCKagura** [comment]
ได้เลยแก้วตา เดี๋ยวลองทำโค้ดดู

**Comment by kaewtar** [comment]
https://drive.google.com/drive/u/1/folders/1U0BG9k2qt0MFRAQZkbZUggIv6ba-4Kwr

**Comment by kaewtar** [comment]
รูปทั้งหมดอยู่ในไดรฟ์นี้นะ

**Comment by kaewtar** [comment]
https://www.canva.com/design/DAFMSQqW6qY/lAZdAb5q4DgEg18MzPbQZw/edit?utm_content=DAFMSQqW6qY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by kaewtar** [comment]
https://www.canva.com/design/DAFMLbI-EFg/rHDni9IRBkGaXn-WK5BsZg/edit?utm_content=DAFMLbI-EFg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by kaewtar** [comment]
https://www.canva.com/design/DAFL7OBmcNE/ZElKss06GleT-dLshaJL8A/edit?utm_content=DAFL7OBmcNE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by kaewtar** [comment]
ตัวละครเสร็จแล้วนะ
