### ISSUE TITLE
background design

### ISSUE THREAD

**Issue by kaewtar** [SCKagura/cpe103-test-group-20#8]

**Comment by kaewtar** [comment]
![road 1](https://user-images.githubusercontent.com/110950048/189345610-4fadbb5c-f5e3-4076-a580-c856f4d754ec.png)

**Comment by SCKagura** [comment]
ขอบคุณมาก เดี๋ยวลองทำโค้ดดู

**Comment by kaewtar** [comment]
ลองดูนะว่าใช้ได้ไหม

**Comment by kaewtar** [comment]
![road no bg](https://user-images.githubusercontent.com/110950048/189347371-2a7b21d1-5d7d-4761-9715-e208f3642cff.png)

**Comment by kaewtar** [comment]
อันนี้เป็นแบบถนนเฉยๆ เราเคยเห็นบางเกมเอาแบบนี้มาต่อกัน

**Comment by kaewtar** [comment]
<img width="768" alt="road 1 (3)" src="https://user-images.githubusercontent.com/110950048/189517319-02b7f671-b999-4c17-83ef-6049a7699d9f.png">

**Comment by kaewtar** [comment]
level 1

**Comment by kaewtar** [comment]
![road 1 (4)](https://user-images.githubusercontent.com/110950048/189522862-9a3d48ba-7880-4eed-b527-632ea5136bd8.png)

**Comment by kaewtar** [comment]
level 2

**Comment by kaewtar** [comment]
![road 1 (5)](https://user-images.githubusercontent.com/110950048/189523823-c234aa00-f399-4285-bbd6-4d2dcdc95d1d.png)

**Comment by kaewtar** [comment]
level3

**Comment by kaewtar** [comment]
![road 1 (6)](https://user-images.githubusercontent.com/110950048/189672721-5a81a394-ac81-40da-8189-02baca269ac7.png)

**Comment by kaewtar** [comment]
![road 1 (6)](https://user-images.githubusercontent.com/110950048/189676737-96595fc1-7c23-43d3-b31c-67c23f14a663.png)

**Comment by kaewtar** [comment]
![road 1 (8)](https://user-images.githubusercontent.com/110950048/189676774-ca8913ee-b17a-4ec8-9724-6369dbef14a7.png)

**Comment by kaewtar** [comment]
![road 1 (8)](https://user-images.githubusercontent.com/110950048/189677137-3f217a4b-86e2-4118-ba5e-5967cf923a89.png)

**Comment by kaewtar** [comment]
![road 1 (7)](https://user-images.githubusercontent.com/110950048/189677264-44b2e6b2-705d-48ab-b141-a333a0548a61.png)

**Comment by kaewtar** [comment]
level 2 3

**Comment by kaewtar** [comment]
![road 1 (9)](https://user-images.githubusercontent.com/110950048/189704173-d2306080-b26e-45a9-829f-0f5a4ce4426a.png)

**Comment by kaewtar** [comment]
![road 1 (10)](https://user-images.githubusercontent.com/110950048/189704271-c4c044cd-8dd1-48dd-96dc-8de69e4839e7.png)
