### ISSUE TITLE
สิ่งกีดขวาง

### ISSUE THREAD

**Issue by Phurinon** [SCKagura/cpe103-test-group-20#9]

**Comment by kaewtar** [comment]
![IMG_0522](https://user-images.githubusercontent.com/110950048/189876969-5e81f92a-ea25-4c03-b458-32770076e3dc.png)

**Comment by kaewtar** [comment]
![Uploading IMG_0523.png…]()
L

**Comment by kaewtar** [comment]
<img width="512" alt="IMG_0525" src="https://user-images.githubusercontent.com/110950048/189877088-5e91509e-ef04-47be-b0ac-b579ba7b7da3.png">

**Comment by kaewtar** [comment]
![IMG_0523](https://user-images.githubusercontent.com/110950048/189877379-3b65c7e5-b489-4226-9268-6844c15c23bb.png)

**Comment by kaewtar** [comment]
![prop (2)](https://user-images.githubusercontent.com/110950048/189931907-0380abad-a8f8-4bea-880e-2f407d8f438c.png)

**Comment by kaewtar** [comment]
![prop (1)](https://user-images.githubusercontent.com/110950048/189931943-006f221f-3392-4aa5-8751-51b42d52f8e7.png)

**Comment by kaewtar** [comment]
![prop](https://user-images.githubusercontent.com/110950048/189931967-91d115e0-7714-46b3-bb16-20905e815439.png)

**Comment by kaewtar** [comment]
![prop (3)](https://user-images.githubusercontent.com/110950048/189933806-f63840f9-ba59-44c0-bbdc-279cbc73bb08.png)
